# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title
gems: [jekyll-paginate]

# Setup
title:               Hopding
tagline:             ''
description:         "Andrew Dillon's blog"
url:                 'http://localhost:4000'
baseurl:             ''
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Andrew Dillon
  description:       Andrew Dillon's blog
  url:               http://hopding.com
  email:             andrew.dillon.j@gmail.com

# Custom vars
version:             1.0.0
